# Generated by Django 5.0.6 on 2024-06-23 15:30

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(blank=True, default='20240606200739Mobile.webp', null=True, upload_to=shop.models.getFileName),
        ),
    ]
